### ISSUE TITLE
Malwarebytes recognizing Ruler.IRule.dll as Malware.Heuristic.1008

### ISSUE THREAD

**Issue by Issgramor** [Steviegt6/ruler#3]
I don't know if this is normal or should I be worried?  The laucher downloaded it through the discord and I was a bit surprised that Malwarebytes detected it as such.

**Comment by Steviegt6** [comment]
Malware.Heuristic.XXXX is a signatureless zero-day detection (https://blog.malwarebytes.com/detections/malware-heuristic/) which is designed to sandbox and analyze the behavior of programs. It's a pretty generic detection and likely picked up on the program's ability to download files from the web, unzip files, and then open processes (this is technically a "payload", which different variants of malware may use). This is a false-positive flagged due to the similar behavior between an installer and a malware payload.

**Comment by Steviegt6** [comment]
I might contact Malwarebytes and ask them to whitelist this program if it proves to be an issue.
